const fs = require('fs');
const path = require('path');
const Module = require('module');
const ROOT = __dirname;
const PUBLIC = path.join(ROOT, 'public');
const SAVE = path.join(ROOT, 'world_career_progress.json');
const PLAYERS_FILE = path.join(PUBLIC, 'players.js');
const COUNTRIES = [
  ['England','Premier Division','Championship','League One','League Two'],['Spain','La Liga','Segunda Division','Primera RFEF','Segunda RFEF'],['Germany','Bundesliga','2. Bundesliga','3. Liga','Regionalliga'],['Italy','Serie A','Serie B','Serie C','Serie D'],['France','Ligue 1','Ligue 2','National','National 2'],['Portugal','Primeira Liga','Liga 2','Liga 3','Campeonato'],['Netherlands','Eredivisie','Eerste Divisie','Tweede Divisie','Derde Divisie'],['Belgium','Pro League','Challenger Pro','National 1','National 2'],['Türkiye','Super Lig','1. Lig','2. Lig','3. Lig'],['Saudi Arabia','Saudi Pro League','First Division','Second Division','Third Division'],['India','Indian Super League','I-League','I-League 2','Regional League'],['Brazil','Serie A','Serie B','Serie C','Serie D'],['Argentina','Liga Profesional','Primera Nacional','Primera B','Primera C'],['Japan','J1 League','J2 League','J3 League','Regional League'],['South Korea','K League 1','K League 2','K4 League','K5 League'],['USA','MLS','USL Championship','USL League One','USL League Two'],['Mexico','Liga MX','Liga de Expansion','Liga Premier','Liga TDP'],['Australia','A-League','NPL Australia','NPL 2','State League'],['Scotland','Premiership','Championship','League One','League Two'],['Austria','Bundesliga','2. Liga','Regionalliga','Landesliga']
];
const CLUB_NAMES={England:['North London FC','Manchester Blue','Merseyside Red','West London United','Midlands City','Tyne Athletic','South Coast FC','Yorkshire United'],Spain:['Madrid CF','Catalunya FC','Sevilla Athletic','Valencia Club','Bilbao United','Vigo FC','Madrid Rovers','Andalucia FC'],Germany:['Munich FC','Dortmund United','Leverkusen 04','Berlin Athletic','Frankfurt FC','Leipzig City','Hamburg SV','Stuttgart 1893'],Italy:['Turin FC','Milano Rosso','Milano Nero','Roma Capital','Napoli Blue','Florence FC','Bologna Athletic','Bergamo United'],France:['Paris FC','Marseille Athletic','Lyon United','Monaco City','Lille OSC','Nice FC','Rennes FC','Lens Athletic'],Portugal:['Lisbon Eagles','Porto Athletic','Braga FC','Guimaraes United','Coimbra FC','Faro City','Madeira FC','Setubal United'],Netherlands:['Amsterdam FC','Rotterdam Athletic','Eindhoven United','Utrecht City','Arnhem FC','Groningen FC','Alkmaar Athletic','Twente United'],Belgium:['Brussels FC','Antwerp United','Bruges Athletic','Liege FC','Ghent City','Genk United','Charleroi FC','Leuven Athletic'],Türkiye:['Istanbul Red','Istanbul Blue','Ankara FC','Izmir Athletic','Trabzon United','Bursa City','Adana FC','Antalya United'],'Saudi Arabia':['Riyadh FC','Jeddah United','Dammam Athletic','Mecca City','Medina FC','Al Khobar United','Abha FC','Taif Athletic'],India:['Mumbai City','Kolkata United','Kerala Athletic','Goa FC','Bengaluru United','Chennai FC','Delhi Athletic','Hyderabad City'],Brazil:['Rio FC','Sao Paulo Athletic','Flamengo City','Minas United','Bahia FC','Gremio Athletic','Parana FC','Pernambuco United'],Argentina:['Buenos Aires FC','Cordoba Athletic','Rosario United','Avellaneda City','Mendoza FC','La Plata Athletic','Tucuman United','Santa Fe FC'],Japan:['Tokyo FC','Osaka Athletic','Yokohama United','Kobe City','Nagoya FC','Saitama Athletic','Kyoto United','Hiroshima FC'],'South Korea':['Seoul FC','Busan United','Incheon Athletic','Daegu City','Jeonbuk FC','Ulsan United','Daejeon Athletic','Suwon FC'],USA:['New York City FC','Los Angeles Athletic','Miami United','Seattle FC','Texas City','Boston Athletic','Chicago United','Atlanta FC'],Mexico:['Mexico City FC','Monterrey United','Guadalajara Athletic','Puebla FC','Tijuana City','Toluca United','Leon FC','Veracruz Athletic'],Australia:['Sydney FC','Melbourne United','Brisbane Athletic','Perth City','Adelaide FC','Newcastle United','Canberra Athletic','Wellington FC'],Scotland:['Glasgow FC','Edinburgh United','Aberdeen Athletic','Dundee City','Hearts United','Hibernian FC','Fife Athletic','Highland FC'],Austria:['Vienna FC','Salzburg United','Graz Athletic','Linz City','Innsbruck FC','Klagenfurt United','Altach Athletic','Wolfsberg FC']};
const MENTALITIES=['Money-Minded','Loyal','Competitive','European Ambition','Star','Playing-Time Focused','Home-Oriented','Career-Minded','Team-Oriented'];
const MANAGER_STYLES=['Possession','Quick Counter','Out Wide','Long Ball Counter','High Press','Balanced','Defensive Block','Youth Development'];
const SPONSORS=['Nova Energy','Vertex Mobile','Pulse Bank','Atlas Motors','Orbit Telecom','NorthStar','Apex Sports','BluePeak','Titan Finance','Urban Cola'];
const COMPETITIONS=[{name:'World Champions Tournament',cadence:'Every 2 seasons',entrants:'Top 4 from each qualifying major league'},{name:'World Elite Cup',cadence:'Every season',entrants:'High-ranked clubs outside Champions field'},{name:'World Challengers Cup',cadence:'Every season',entrants:'Emerging and lower-division clubs'},{name:'Regional Promotion Cup',cadence:'Every season',entrants:'Lower-tier qualification winners'}];
function clamp(n,a,b){return Math.max(a,Math.min(b,n));} function hash(s){let h=0;for(const c of String(s))h=(h*31+c.charCodeAt(0))|0;return Math.abs(h);} function uid(p){return p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);} function clone(x){return JSON.parse(JSON.stringify(x));}
function loadPlayers(){try{delete require.cache[require.resolve(PLAYERS_FILE)];const p=require(PLAYERS_FILE);return Array.isArray(p)?p:[];}catch(e){return[];}}
function makeClub(country,div,i,name){const seed=`${country}-${div}-${i}`,rep=clamp(88-div*13+(hash(seed)%12)-6,35,96);return{id:seed,name,country,division:div,reputation:rep,fans:Math.round(12000+rep*2400+(hash(seed+'f')%9000)),fanSatisfaction:clamp(62+(hash(seed+'s')%30),35,98),morale:clamp(60+(hash(seed+'m')%34),40,96),cash:Math.round(25+rep*1.4+(hash(seed+'c')%30)),stadiumLevel:1+Math.floor(rep/25),stadiumCapacity:12000+Math.floor(rep/10)*2500,ticketPrice:500+Math.floor(rep/20)*100,merchandise:50+Math.floor(rep/3),sponsor:{name:SPONSORS[hash(seed+'sp')%SPONSORS.length],value:Math.round(4+rep/8),years:1+(hash(seed)%3),objective:'Finish above your previous league position'},titles:0,promotions:0,relegations:0,history:[],manager:null,jersey:{home:'#101b2d',away:'#e8edf4',third:'#263b55',quality:50},merchSales:0,financeLog:[]};}
function buildClubs(){const out=[];for(const [country,...divs] of COUNTRIES){const names=CLUB_NAMES[country]||[];divs.forEach((league,di)=>{for(let i=0;i<8;i++)out.push(makeClub(country,di+1,i,names[i]?(di?`${names[i]} ${di+1}`:names[i]):`${country} Club ${i+1} D${di+1}`));});}return out;}
function seedMarket(){const out=[],seen=new Set();for(const p of loadPlayers()){const n=String(p.name||'').trim(),key=n.toLowerCase();if(!n||seen.has(key))continue;seen.add(key);const rating=Number(p.rating||p.overall||p.ovr||80);if(rating<65)continue;const price=Math.max(3,Math.round((Number(p.base)||rating/12)*1.2));out.push({...p,name:n,rating,marketValue:price,askingPrice:price,mentality:MENTALITIES[hash(n)%MENTALITIES.length],mentalityStrength:72+(hash(n)%25),contractYears:1+(hash(n+'y')%4),salary:Math.max(1,Math.round(price*.12)),releaseClause:Math.max(price,Math.round(price*1.67)),ownerClub:String(p.club||p.team||'Free Agent'),form:clamp(65+(hash(n+'form')%35),50,99),status:'available'});if(out.length>=260)break;}return out;}
function seedManagers(){const first=['Marco','Daniel','Luca','Alex','Rafael','Thomas','Jorge','Arun','Victor','Miguel','Kenji','Samuel','Andre','David','Leon','Milan','Oliver','Nico','Sergio','Yuki'],last=['Costa','Silva','Muller','Rossi','Fernandez','Bauer','Nakamura','Mehta','Santos','Kovac','Martin','Alves'];const out=[];for(let i=0;i<60;i++){const name=`${first[i%first.length]} ${last[(i*7)%last.length]}`,style=MANAGER_STYLES[i%MANAGER_STYLES.length],rating=68+(hash(name)%29);out.push({id:'MGR-'+i,name,rating,style,preferredFormations:style==='Possession'?['4-3-3','4-2-3-1']:style==='Quick Counter'?['4-2-3-1','4-4-2']:style==='Out Wide'?['4-4-2','4-3-3']:style==='High Press'?['4-3-3','3-4-3']:['4-4-2','4-2-3-1'],attack:55+(hash(name+'a')%40),defence:55+(hash(name+'d')%40),youth:55+(hash(name+'y')%45),recruitment:55+(hash(name+'r')%45),salary:Math.round(2+rating*.08),askingPrice:Math.round(5+rating*.35),releaseClause:Math.round(8+rating*.6),contractYears:1+(i%3),reputation:rating,status:'available'});}return out;}
function newWorld(mode='solo',roomCode=null){return{version:3,roomCode,mode,season:1,transferWindow:'summer',transferWindowOpen:true,selectedClub:null,clubs:buildClubs(),market:seedMarket(),managers:seedManagers(),offers:[],managerOffers:[],news:[{id:uid('news'),season:1,type:'World',text:'The football world is ready for a new season.'}],completedMatches:{},worldTournament:null};}
const rooms=new Map(),soloWorlds=new Map();
function pushNews(w,text,type='World'){w.news.unshift({id:uid('news'),season:w.season,type,text});w.news=w.news.slice(0,60);}
function findClub(w,name){return w.clubs.find(c=>c.name===name)||null;}
function refreshEconomy(c){const attendance=Math.round(clamp(c.stadiumCapacity*(.35+c.fanSatisfaction/160+c.reputation/250),100,c.stadiumCapacity));c.lastAttendance=attendance;c.ticketRevenue=Math.round(attendance*c.ticketPrice/1000000);c.merchSales=Math.round(c.merchandise*(c.fans/10000)*((c.reputation/100)+.35)*(c.jersey.quality/100));c.sponsorRevenue=c.sponsor.value;}
function interest(c,p){if(!c)return 0;let s=c.reputation*.45+c.fanSatisfaction*.08+c.morale*.07+(c.division===1?15:c.division===2?7:0);if(p.mentality==='Money-Minded')s+=Math.min(20,c.cash/10);if(p.mentality==='Loyal'&&p.ownerClub===c.name)s+=20;if(p.mentality==='Competitive')s+=c.reputation*.15;if(p.mentality==='European Ambition')s+=c.reputation>=80?18:0;if(p.mentality==='Playing-Time Focused')s+=c.division>1?10:-2;if(p.mentality==='Career-Minded')s+=c.reputation>=75?12:0;return Math.round(clamp(s,0,99));}
function recommendations(w,c){if(!c)return[];const m=c.manager;if(!m)return w.market.filter(p=>p.status!=='sold').sort((a,b)=>b.rating-a.rating).slice(0,8);const wanted=m.style==='Possession'?['CMF','DMF','AMF','LB','RB']:m.style==='Quick Counter'?['CF','LWF','RWF','AMF']:m.style==='High Press'?['CF','CMF','CB','RB','LB']:m.style==='Defensive Block'?['CB','DMF','GK']:['CF','CMF','CB'];return w.market.map(p=>({...p,fit:(wanted.includes(String(p.position||'').toUpperCase())?25:0)+Number(p.rating||0)+interest(c,p)*.15})).sort((a,b)=>b.fit-a.fit).slice(0,8);}
function transferOffer(w,from,to,playerName,fee,salary,years,kind='buy'){const p=w.market.find(x=>x.name===playerName),buyer=findClub(w,from),seller=findClub(w,to)||findClub(w,p?.ownerClub);if(!p||!buyer)return{error:'Player or buyer club not found'};if(!w.transferWindowOpen)return{error:'Transfer window is closed'};fee=Number(fee)||p.askingPrice;salary=Number(salary)||p.salary;years=Number(years)||3;if(kind==='buy'&&fee>buyer.cash)return{error:'Insufficient club funds'};const o={id:uid('offer'),from,to:seller?seller.name:(to||p.ownerClub),player:playerName,fee,salary,years,kind,interest:interest(buyer,p),deadline:Date.now()+180000,status:'pending',createdAt:Date.now()};w.offers.push(o);pushNews(w,`${from} submitted a ${kind} offer for ${playerName}: ₹${fee}M + ₹${salary}M/year.`,'Transfer Battle');return o;}
function decideOffer(w,id,decision,data){const o=w.offers.find(x=>x.id===id);if(!o)return{error:'Offer not found'};if(Date.now()>o.deadline&&decision!=='accept')o.status='expired';if(o.status==='expired')return o;if(decision==='reject'){o.status='rejected';return o;}if(decision==='counter'){o.status='counter';o.fee=Number(data?.fee)||o.fee;o.salary=Number(data?.salary)||o.salary;o.deadline=Date.now()+120000;return o;}const p=w.market.find(x=>x.name===o.player),buyer=findClub(w,o.from),seller=findClub(w,o.to);if(!p||!buyer)return{error:'Invalid transfer'};if(o.kind==='buy'&&o.fee>buyer.cash)return{error:'Insufficient funds'};const willingness=clamp((o.interest||0)+o.salary*.7,0,130);if(willingness<50){o.status='rejected-player';pushNews(w,`${p.name} rejected ${o.from} because the club did not fit the player's ambitions.`,'Player Decision');return o;}if(seller&&o.kind==='buy')seller.cash+=o.fee;if(o.kind==='buy'){buyer.cash=Math.max(0,buyer.cash-o.fee);p.ownerClub=buyer.name;p.salary=o.salary;p.contractYears=o.years;p.releaseClause=Math.round(o.fee*1.67);p.status='contracted';}else{p.loanClub=buyer.name;p.loanYears=o.years;p.status='loaned';}o.status='accepted';w.offers.filter(x=>x.player===p.name&&x.status==='pending'&&x.id!==o.id).forEach(x=>x.status='hijacked');pushNews(w,`${p.name} completed a ${o.kind} move to ${buyer.name}.`,'Transfer Complete');return o;}
function sellPlayer(w,clubName,playerName,asking){const p=w.market.find(x=>x.name===playerName),c=findClub(w,clubName);if(!p||!c)return{error:'Player not found'};p.ownerClub=c.name;p.askingPrice=Number(asking)||p.askingPrice;p.status='listed';pushNews(w,`${c.name} listed ${p.name} for transfer at ₹${p.askingPrice}M.`,'Transfer Market');return p;}
function releasePlayer(w,clubName,playerName){const p=w.market.find(x=>x.name===playerName);if(!p||p.ownerClub!==clubName)return{error:'This club does not own the player'};p.ownerClub='Free Agent';p.status='free-agent';p.contractYears=0;p.releaseClause=0;pushNews(w,`${clubName} released ${p.name}; the player is now a free agent.`,'Transfer Market');return p;}
function loanPlayer(w,from,to,playerName,fee,years){return transferOffer(w,to,from,playerName,fee,0,years||1,'loan');}
function hireManager(w,clubName,managerId,salary,years){const c=findClub(w,clubName),m=w.managers.find(x=>x.id===managerId);if(!c||!m)return{error:'Manager not found'};salary=Number(salary)||m.salary;years=Number(years)||m.contractYears;if(salary>c.cash)return{error:'Insufficient funds'};c.cash-=salary;c.manager={...m,salary,contractYears:years,status:'hired',club:c.name};m.status='hired';m.club=c.name;pushNews(w,`${clubName} appointed ${m.name}, a ${m.style} manager.`,'Manager Market');return c.manager;}
function managerOffer(w,clubName,managerId,salary,years){const c=findClub(w,clubName),m=w.managers.find(x=>x.id===managerId);if(!c||!m)return{error:'Manager not found'};const o={id:uid('moffer'),club:clubName,managerId,manager:m.name,salary:Number(salary)||m.salary,years:Number(years)||m.contractYears,deadline:Date.now()+120000,status:'pending'};w.managerOffers.push(o);return o;}
function simulateMatch(w,clubName,opponentName){const a=findClub(w,clubName),b=findClub(w,opponentName);if(!a||!b)return{error:'Club not found'};const key=`S${w.season}:${[a.id,b.id].sort().join(':')}`;if(w.completedMatches[key])return w.completedMatches[key];const seed=hash(key),home=Math.max(0,Math.round((a.reputation-b.reputation)/18+(seed%4)-1)),away=Math.max(0,Math.round((b.reputation-a.reputation)/20+((seed>>3)%3)-1));const result={id:key,home:a.name,away:b.name,homeGoals:home,awayGoals:away,played:true,season:w.season};w.completedMatches[key]=result;refreshEconomy(a);const starBoost=w.market.filter(p=>p.ownerClub===a.name&&Number(p.rating)>=88).length*3,merchBoost=Math.round((a.jersey.quality/100)*a.fans/20000)+starBoost;a.cash+=a.ticketRevenue+Math.max(1,Math.round(a.sponsor.value/4))+merchBoost;a.fans=clamp(a.fans+(home>away?Math.round(a.fans*.01):home<away?-Math.round(a.fans*.004):Math.round(a.fans*.001)),1000,999999999);a.fanSatisfaction=clamp(a.fanSatisfaction+(home>away?3:home<away?-4:0),20,99);a.morale=clamp(a.morale+(home>away?2:home<away?-3:0),20,99);pushNews(w,`${a.name} ${home>away?'won':home<away?'lost':'drew'} ${home}-${away} against ${b.name}. Ticket revenue ₹${a.ticketRevenue}M.`,'Match');return result;}
function advanceSeason(w){w.season++;w.transferWindowOpen=true;w.transferWindow='summer';for(const c of w.clubs){const swing=(hash(c.name+w.season)%9)-4;c.morale=clamp(c.morale+swing,30,99);c.fanSatisfaction=clamp(c.fanSatisfaction+(c.morale>75?2:-2),20,99);refreshEconomy(c);c.cash=Math.max(0,Math.round(c.cash+c.sponsor.value+c.ticketRevenue+c.merchSales-(c.manager?c.manager.salary:2)-5));if(c.division>1&&hash(c.name+w.season)%100<10){c.division--;c.promotions++;c.reputation=clamp(c.reputation+3,1,99);pushNews(w,`${c.name} won promotion.`,'League');}else if(c.division<4&&hash(c.name+'r'+w.season)%100<8){c.division++;c.relegations++;c.reputation=clamp(c.reputation-3,1,99);pushNews(w,`${c.name} was relegated.`,'League');}if(c.manager&&c.manager.contractYears>0)c.manager.contractYears--;c.history.unshift({season:w.season,division:c.division,rep:c.reputation,cash:c.cash});c.history=c.history.slice(0,10);}for(const p of w.market){p.form=clamp(p.form+(hash(p.name+w.season)%13)-6,45,99);if(p.contractYears>0)p.contractYears--;if(p.contractYears===0&&p.status!=='loaned')p.status='free-agent';}for(const m of w.managers){if(m.status==='available')m.reputation=clamp(m.reputation+(hash(m.name+w.season)%7)-3,55,99);}w.completedMatches={};w.worldTournament=w.season%2===0?{name:'World Champions Tournament',season:w.season,status:'Qualifying'}:null;pushNews(w,`Season ${w.season} begins across ${COUNTRIES.length} countries.`,'World');if(w.worldTournament)pushNews(w,'The World Champions Tournament qualification cycle is open.','Global Competition');}
function setJersey(w,clubName,data){const c=findClub(w,clubName);if(!c)return{error:'Club not found'};c.jersey={...c.jersey,...data};c.jersey.quality=clamp(Number(c.jersey.quality)||50,0,100);c.merchandise=clamp(Math.round(40+c.jersey.quality*.9+c.reputation*.25),10,300);pushNews(w,`${c.name} launched a new kit collection. Estimated jersey demand is ${c.jersey.quality}%.`,'Merchandise');return c;}
function stadiumUpgrade(w,clubName,action,value){const c=findClub(w,clubName);if(!c)return{error:'Club not found'};if(action==='capacity'){if(c.cash<12)return{error:'Not enough funds'};c.cash-=12;c.stadiumLevel++;c.stadiumCapacity+=10000;c.reputation=clamp(c.reputation+2,1,99);}if(action==='ticket')c.ticketPrice=clamp(Number(value)||c.ticketPrice,100,5000);return c;}
function sponsorship(w,clubName,name){const c=findClub(w,clubName);if(!c)return{error:'Club not found'};c.sponsor={name:name||SPONSORS[hash(c.name+w.season)%SPONSORS.length],value:Math.max(4,Math.round(c.reputation/9)),years:2+(hash(c.name)%2),objective:c.reputation>75?'Qualify for continental competition':'Finish above your previous league position'};pushNews(w,`${c.name} signed a ${c.sponsor.years}-season sponsorship with ${c.sponsor.name}.`,'Sponsorship');return c.sponsor;}
function createClub(w,d){const name=String(d?.name||'').trim();if(!name)return{error:'Club name required'};if(w.clubs.some(c=>c.name.toLowerCase()===name.toLowerCase()))return{error:'Club name already exists'};const country=d.country||'India',div=Number(d.division)||3;const c=makeClub(country,div,hash(name)%9999,name);c.id=uid('club');c.reputation=50;c.fans=10000;c.cash=50;c.manager=null;c.jersey={home:d.home||'#10243b',away:d.away||'#e8edf4',third:d.third||'#253d59',quality:Number(d.quality)||70};c.merchandise=clamp(Math.round(40+c.jersey.quality*.9),10,300);c.stadiumCapacity=10000;c.ticketPrice=500;w.clubs.push(c);w.selectedClub=c.name;pushNews(w,`${name} was created in ${country}, Division ${div}.`,'Club Creation');return c;}
function worldSnapshot(w){return{season:w.season,mode:w.mode,roomCode:w.roomCode,transferWindow:w.transferWindow,transferWindowOpen:w.transferWindowOpen,selectedClub:w.selectedClub,clubs:w.clubs,market:w.market,managers:w.managers,offers:w.offers,managerOffers:w.managerOffers,news:w.news,competitions:COMPETITIONS,worldTournament:w.worldTournament,countries:COUNTRIES.map(([country,...leagues])=>({country,leagues})),recommendations:recommendations(w,findClub(w,w.selectedClub)),rooms:[...rooms.values()].map(r=>({code:r.code,name:r.name,max:r.maxHumans,count:Object.keys(r.humans).length,host:r.hostName}))};}
function makeRoom(name,max,hostSocket,hostName){let code;do{code=Math.random().toString(36).slice(2,8).toUpperCase();}while(rooms.has(code));const r={code,name:name||'Friends Football World',maxHumans:clamp(Number(max)||10,2,20),hostSocket,hostName:hostName||'Host',humans:{},world:newWorld('online',code)};rooms.set(code,r);return r;}
function joinRoom(code,socketId,name){const r=rooms.get(String(code||'').toUpperCase());if(!r)return{error:'Room not found'};if(Object.keys(r.humans).length>=r.maxHumans&&!r.humans[socketId])return{error:'Room is full'};r.humans[socketId]={name:name||'Manager',club:null,joinedAt:Date.now()};return r;}
function currentWorld(socket){if(socket.__worldRoom&&rooms.has(socket.__worldRoom))return rooms.get(socket.__worldRoom).world;if(socket.__soloId&&soloWorlds.has(socket.__soloId))return soloWorlds.get(socket.__soloId);return null;}
function saveSolo(w){try{fs.writeFileSync(SAVE,JSON.stringify(w,null,2));}catch(e){}}
function installExpress(app){if(app.__worldFeaturesInstalled)return;app.__worldFeaturesInstalled=true;app.use((req,res,next)=>{if((req.path==='/'||req.path==='/index.html')&&req.method==='GET'){try{let html=fs.readFileSync(path.join(PUBLIC,'index.html'),'utf8');const tag='<link rel="stylesheet" href="/world_features.css"><script src="/world_features_client.js"></script>';if(!html.includes('/world_features_client.js'))html=html.replace('</head>',tag+'</head>');return res.type('html').send(html);}catch(e){}}next();});
app.get('/api/world/state',(req,res)=>{const w=currentWorld({__worldRoom:req.query.room,__soloId:req.query.soloId});res.json(worldSnapshot(w||newWorld('solo')));});
app.get('/api/world/rooms',(req,res)=>res.json([...rooms.values()].map(r=>({code:r.code,name:r.name,max:r.maxHumans,count:Object.keys(r.humans).length,host:r.hostName}))));
app.post('/api/world/room/create',(req,res)=>{const r=makeRoom(req.body?.name,req.body?.maxHumans,null,req.body?.managerName);res.json({code:r.code,name:r.name,maxHumans:r.maxHumans,state:worldSnapshot(r.world)});});
app.post('/api/world/room/join',(req,res)=>{const r=joinRoom(req.body?.code,req.body?.socketId,req.body?.managerName);if(r.error)return res.status(400).json(r);res.json({code:r.code,state:worldSnapshot(r.world)});});
app.post('/api/world/solo/create',(req,res)=>{const id=uid('solo'),w=newWorld('solo');soloWorlds.set(id,w);res.json({soloId:id,state:worldSnapshot(w)});});
app.post('/api/world/career',(req,res)=>{const w=currentWorld({__worldRoom:req.body?.room,__soloId:req.body?.soloId});if(!w)return res.status(400).json({error:'Enter a world first'});const c=findClub(w,req.body?.club)||w.clubs.find(x=>x.country===req.body?.country&&x.division===Number(req.body?.division));if(!c)return res.status(404).json({error:'Club not found'});w.selectedClub=c.name;w.mode=req.body?.mode||w.mode;if(w.mode==='solo')saveSolo(w);res.json({club:c,state:worldSnapshot(w)});});
app.post('/api/world/club/create',(req,res)=>{const w=currentWorld({__worldRoom:req.body?.room,__soloId:req.body?.soloId})||newWorld(req.body?.mode||'solo');res.json(createClub(w,req.body));});
app.post('/api/world/offer',(req,res)=>{const w=currentWorld({__worldRoom:req.body?.room,__soloId:req.body?.soloId});res.json(w?transferOffer(w,req.body?.from,req.body?.to,req.body?.player,req.body?.fee,req.body?.salary,req.body?.years,req.body?.kind||'buy'):{error:'World not found'});});
app.post('/api/world/offer/:id',(req,res)=>{const w=currentWorld({__worldRoom:req.body?.room,__soloId:req.body?.soloId});const o=w?.offers.find(x=>x.id===req.params.id);res.json(w&&o?decideOffer(w,o.id,req.body?.decision,req.body):{error:'Offer not found'});});
app.post('/api/world/sell',(req,res)=>{const w=currentWorld({__worldRoom:req.body?.room,__soloId:req.body?.soloId});res.json(sellPlayer(w,req.body?.club,req.body?.player,req.body?.askingPrice));});
app.post('/api/world/release',(req,res)=>{const w=currentWorld({__worldRoom:req.body?.room,__soloId:req.body?.soloId});res.json(releasePlayer(w,req.body?.club,req.body?.player));});
app.post('/api/world/loan',(req,res)=>{const w=currentWorld({__worldRoom:req.body?.room,__soloId:req.body?.soloId});res.json(loanPlayer(w,req.body?.from,req.body?.to,req.body?.player,req.body?.fee,req.body?.years));});
app.post('/api/world/hijack',(req,res)=>{const w=currentWorld({__worldRoom:req.body?.room,__soloId:req.body?.soloId});res.json(w?transferOffer(w,req.body?.from,req.body?.to,req.body?.player,req.body?.fee,req.body?.salary,req.body?.years,'buy'):{error:'World not found'});});
app.post('/api/world/manager/offer',(req,res)=>{const w=currentWorld({__worldRoom:req.body?.room,__soloId:req.body?.soloId});res.json(managerOffer(w,req.body?.club,req.body?.managerId,req.body?.salary,req.body?.years));});
app.post('/api/world/manager/hire',(req,res)=>{const w=currentWorld({__worldRoom:req.body?.room,__soloId:req.body?.soloId});res.json(hireManager(w,req.body?.club,req.body?.managerId,req.body?.salary,req.body?.years));});
app.post('/api/world/simulate',(req,res)=>{const w=currentWorld({__worldRoom:req.body?.room,__soloId:req.body?.soloId});res.json(w?simulateMatch(w,req.body?.club,req.body?.opponent):{error:'World not found'});});
app.post('/api/world/advance-season',(req,res)=>{const w=currentWorld({__worldRoom:req.body?.room,__soloId:req.body?.soloId});if(!w)return res.status(400).json({error:'World not found'});advanceSeason(w);if(w.mode==='solo')saveSolo(w);res.json(worldSnapshot(w));});
app.post('/api/world/transfer-window',(req,res)=>{const w=currentWorld({__worldRoom:req.body?.room,__soloId:req.body?.soloId});if(!w)return res.status(400).json({error:'World not found'});w.transferWindowOpen=Boolean(req.body?.open);w.transferWindow=req.body?.type||(w.transferWindowOpen?'summer':'closed');pushNews(w,`The ${w.transferWindow} transfer window is now ${w.transferWindowOpen?'open':'closed'}.`,'Transfer Window');res.json(worldSnapshot(w));});
app.post('/api/world/jersey',(req,res)=>{const w=currentWorld({__worldRoom:req.body?.room,__soloId:req.body?.soloId});res.json(setJersey(w,req.body?.club,req.body));});
app.post('/api/world/stadium',(req,res)=>{const w=currentWorld({__worldRoom:req.body?.room,__soloId:req.body?.soloId});res.json(stadiumUpgrade(w,req.body?.club,req.body?.action,req.body?.value));});
app.post('/api/world/sponsor',(req,res)=>{const w=currentWorld({__worldRoom:req.body?.room,__soloId:req.body?.soloId});res.json(sponsorship(w,req.body?.club,req.body?.name));});
}
function installSocket(io){if(io.__worldFeaturesInstalled)return;io.__worldFeaturesInstalled=true;io.on('connection',socket=>{
 socket.on('world:soloCreate',()=>{const id=uid('solo'),w=newWorld('solo');soloWorlds.set(id,w);socket.__soloId=id;socket.emit('world:session',{type:'solo',soloId:id,state:worldSnapshot(w)});});
 socket.on('world:createRoom',d=>{const r=makeRoom(d?.name,d?.maxHumans,socket.id,d?.managerName);r.humans[socket.id]={name:d?.managerName||'Host',club:null,joinedAt:Date.now()};socket.__worldRoom=r.code;socket.join(r.code);socket.emit('world:session',{type:'online',roomCode:r.code,state:worldSnapshot(r.world)});io.emit('world:rooms',[...rooms.values()].map(x=>({code:x.code,name:x.name,max:x.maxHumans,count:Object.keys(x.humans).length,host:x.hostName})));});
 socket.on('world:joinRoom',d=>{const r=joinRoom(d?.code,socket.id,d?.managerName);if(r.error){socket.emit('world:error',r);return;}socket.__worldRoom=r.code;socket.join(r.code);socket.emit('world:session',{type:'online',roomCode:r.code,state:worldSnapshot(r.world)});io.to(r.code).emit('worldState',worldSnapshot(r.world));});
 socket.on('world:career',d=>{const w=currentWorld(socket);if(!w)return;const c=findClub(w,d?.club)||w.clubs.find(x=>x.country===d?.country&&x.division===Number(d?.division));if(c){w.selectedClub=c.name;w.mode=d?.mode||w.mode;if(socket.__worldRoom)rooms.get(socket.__worldRoom).humans[socket.id].club=c.name;socket.emit('worldState',worldSnapshot(w));io.to(socket.__worldRoom||socket.id).emit('worldState',worldSnapshot(w));}});
 socket.on('world:createClub',d=>{const w=currentWorld(socket);if(!w)return;const c=createClub(w,d);socket.emit('worldState',worldSnapshot(w));if(socket.__worldRoom)io.to(socket.__worldRoom).emit('worldState',worldSnapshot(w));});
 socket.on('world:offer',d=>{const w=currentWorld(socket);if(!w)return;const o=transferOffer(w,d?.from,d?.to,d?.player,d?.fee,d?.salary,d?.years,d?.kind||'buy');io.to(socket.__worldRoom||socket.id).emit('transferBattle',o);io.to(socket.__worldRoom||socket.id).emit('worldState',worldSnapshot(w));});
 socket.on('world:hijack',d=>{const w=currentWorld(socket);if(!w)return;const o=transferOffer(w,d?.from,d?.to,d?.player,d?.fee,d?.salary,d?.years,'buy');if(!o.error)pushNews(w,`${d?.from} entered a live hijack battle for ${d?.player}.`,'Hijack Alert');io.to(socket.__worldRoom||socket.id).emit('transferBattle',o);io.to(socket.__worldRoom||socket.id).emit('worldState',worldSnapshot(w));});
 socket.on('world:simulate',d=>{const w=currentWorld(socket);if(!w)return;const result=simulateMatch(w,d?.club,d?.opponent);io.to(socket.__worldRoom||socket.id).emit('matchSimulated',result);io.to(socket.__worldRoom||socket.id).emit('worldState',worldSnapshot(w));});
 socket.on('world:advanceSeason',()=>{const w=currentWorld(socket);if(!w)return;advanceSeason(w);if(w.mode==='solo')saveSolo(w);io.to(socket.__worldRoom||socket.id).emit('worldState',worldSnapshot(w));});
 socket.on('disconnect',()=>{if(socket.__worldRoom&&rooms.has(socket.__worldRoom)){const r=rooms.get(socket.__worldRoom);delete r.humans[socket.id];if(Object.keys(r.humans).length===0)rooms.delete(r.code);}});
});}
const originalLoad=Module._load;
Module._load=function(request,parent,isMain){if(request==='express'){const original=originalLoad.apply(this,arguments);if(original.__worldWrapped)return original;function wrappedExpress(...args){const app=original(...args);installExpress(app);return app;}Object.assign(wrappedExpress,original);wrappedExpress.__worldWrapped=true;return wrappedExpress;}if(request==='socket.io'){const original=originalLoad.apply(this,arguments);if(original.__worldWrapped)return original;const OriginalServer=original.Server;class WorldServer extends OriginalServer{constructor(...args){super(...args);installSocket(this);}}return{...original,Server:WorldServer,__worldWrapped:true};}return originalLoad.apply(this,arguments);};
